# Generated by Django 4.2 on 2025-02-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("email", models.TextField()),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("password", models.TextField()),
            ],
        ),
    ]
